[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
leptos = "0.5.2"
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tokio = { version = "1.33.0", features = ["full"] }