name: Build, push, and run image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: matvey-docker
      AWS_HOST: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: AWS ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Drop last image from ECR
        run: |
          aws ecr batch-delete-image --repository-name $IMAGE_NAME --image-ids imageTag=latest || true

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $IMAGE
          docker push $IMAGE

      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-169-18-53.eu-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true
            aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $AWS_HOST
            docker pull $IMAGE
            docker run -d \
              --name matvey-app \
              -p 80:8080 \
              $IMAGE
