name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_HOST: 667377285515.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: matvey-docker
      IMAGE: "${{ env.AWS_HOST }}/${{ env.IMAGE_NAME }}:latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: AWS ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Drop last image from ECR
        run: |
          aws ecr batch-delete-image --repository-name matvey-docker --image-ids imageTag=latest || true

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $IMAGE
          docker push $IMAGE
