name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: AWS ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Drop last image from ECR
        run: |
          aws ecr batch-delete-image --repository-name matvey-docker --image-ids imageTag=latest || true

      - name: Build Docker image
        run: |
          docker build -t matvey-docker .
          docker tag matvey-docker:latest 667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest
          docker push 667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest 
