name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: matvey-app
      IMAGE_NAME: matvey-docker
      AWS_HOST: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest

    steps:
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-169-18-53.eu-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true
            aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ env.AWS_HOST }}
            docker pull ${{ env.IMAGE }} 
            docker run -d \
              --name ${{ env.APP_NAME }} \
              -p 80:8080 \
              ${{ env.IMAGE }}
